name: Production

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

jobs:
  deploy:
    if: ${{github.event_name == 'workflow_dispatch' || ( github.event.pull_request.merged == true && startsWith(github.head_ref, 'chore/release' ))}}
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: verify
        run: echo "this was run"
